# SPDX-FileCopyrightText: 2026 AerynOS Developers
# SPDX-License-Identifier: MPL-2.0

[default]
extend-ignore-re = [
    # Ignore blocks between `spellchecker:off` and `spellchecker:on`
    "spellchecker:off.*?\\n*.*spellchecker:on",
]
extend-ignore-words-re = [
    # Specifically for the "General FAQ" page.
    '\"aer\"',
]

[files]
extend-exclude = ["/package-lock.json"]
